import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Plus, Bell, Trash2, Sparkles, CheckCircle2, Clock } from 'lucide-react';
import { useAppData } from '../hooks/useAppData';
import { mockGemini } from '../utilities/mockGemini';

export default function DrillManager({ onToast }) {
  const { data, updateDrills } = useAppData();
  const drills = data.drills;
  const [form, setForm] = useState({ title: '', type: 'Fire' });
  const [generating, setGenerating] = useState(false);

  const scheduleDrill = (e) => {
    e.preventDefault();
    if (!form.title.trim()) {
      onToast('Please enter a drill title.', 'warn');
      return;
    }
    updateDrills(prev => [
      {
        id: 'd-' + Date.now(),
        title: form.title.trim(),
        type: form.type.toLowerCase(),
        timestamp: Date.now(),
        status: 'Completed'
      },
      ...prev
    ]);
    onToast('Drill safety record logged successfully!', 'success');
    setForm({ title: '', type: 'Fire' });
  };

  const deleteDrill = (id) => {
    if (window.confirm('Are you sure you want to delete this drill log from history?')) {
      updateDrills(prev => prev.filter(d => d.id !== id));
      onToast('Drill safety log deleted.', 'info');
    }
  };

  const handleAiGenerate = async () => {
    setGenerating(true);
    try {
      const prompt = `Generate a realistic 1-sentence emergency drill alert title for a university campus for a ${form.type} emergency. Keep it under 60 characters. Do not use quotes or prefixes.`;
      const result = await mockGemini.generate(prompt, "You are a campus safety officer writing drill alerts.");
      // Clean up the output string if any quotes are returned
      const cleanTitle = result.trim().replace(/^"|"$/g, '');
      setForm(prev => ({ ...prev, title: cleanTitle }));
      onToast('Dynamic scenario alert generated by Gemini!', 'success');
    } catch (e) {
      onToast('Simulated AI Generation failed.', 'error');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto text-white">
      {/* Header */}
      <div>
        <span className="font-mono text-xs font-bold uppercase tracking-widest text-red-500">▶ Safety Coordinator Logs</span>
        <h1 className="text-3xl font-extrabold tracking-tight text-slate-100 font-sans">Drill Manager</h1>
      </div>

      {/* Record Form */}
      <div className="rounded-2xl border-l-4 border-l-red-500 border-y border-r border-slate-800 bg-slate-900/20 p-6 backdrop-blur-sm shadow-xl">
        <div className="flex justify-between items-baseline mb-4">
          <h3 className="text-lg font-bold text-white">Record New Drill</h3>
          <button
            onClick={handleAiGenerate}
            disabled={generating}
            className="text-xs font-bold text-red-500 hover:text-red-400 inline-flex items-center gap-1.5 focus:outline-none disabled:opacity-50"
          >
            <Sparkles className="h-3.5 w-3.5" />
            {generating ? 'Generating scenario...' : 'Auto-Generate Alert'}
          </button>
        </div>

        <form onSubmit={scheduleDrill} className="flex flex-col md:flex-row gap-4 items-end">
          <div className="flex-1 w-full">
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Drill Title</label>
            <input
              type="text"
              required
              value={form.title}
              onChange={e => setForm({ ...form, title: e.target.value })}
              placeholder="e.g. Science Annex Evacuation Path Testing"
              className="w-full rounded-xl border border-slate-800 bg-slate-950 px-4 py-3 text-sm text-white placeholder-slate-600 focus:border-red-500 focus:outline-none transition-colors"
            />
          </div>
          <div className="w-full md:w-48">
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Hazard Type</label>
            <select
              value={form.type}
              onChange={e => setForm({ ...form, type: e.target.value })}
              className="w-full rounded-xl border border-slate-800 bg-slate-950 px-4 py-3 text-sm text-white focus:border-red-500 focus:outline-none transition-colors cursor-pointer"
            >
              <option>Fire</option>
              <option>Flood</option>
              <option>Quake</option>
              <option>Threat</option>
            </select>
          </div>
          <button
            type="submit"
            className="w-full md:w-auto rounded-xl bg-red-600 hover:bg-red-500 px-6 py-3 text-sm font-bold text-white transition-all flex items-center justify-center gap-2 shadow-lg shadow-red-600/20"
          >
            <Plus className="h-4.5 w-4.5" /> Schedule Drill
          </button>
        </form>
      </div>

      {/* Drill Logs History */}
      <div className="space-y-4">
        <span className="font-mono text-xs font-bold uppercase tracking-wider text-slate-500">▶ Safety drill timeline logs</span>

        {drills.length === 0 ? (
          <div className="rounded-2xl border border-slate-800 bg-slate-900/10 p-12 text-center text-slate-500 font-medium">
            No safety drills logged in current local storage.
          </div>
        ) : (
          <div className="space-y-3">
            {drills.map((d) => (
              <div
                key={d.id}
                className="rounded-xl border border-slate-800 bg-slate-900/40 p-4 backdrop-blur-sm flex items-center justify-between gap-4 hover:border-slate-700/80 transition-colors"
              >
                <div className="min-w-0">
                  <h4 className="text-base font-bold text-slate-200 truncate">{d.title}</h4>
                  <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-slate-500 font-mono mt-1">
                    <span>{new Date(d.timestamp).toLocaleString()}</span>
                    <span>•</span>
                    <span className="uppercase text-slate-400 font-semibold">{d.type} Drill</span>
                  </div>
                </div>

                <div className="flex items-center gap-4 flex-shrink-0">
                  <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-[9px] font-extrabold tracking-wider uppercase border ${
                    d.status === 'Completed'
                      ? 'border-emerald-500/20 bg-emerald-500/10 text-emerald-400'
                      : 'border-orange-500/20 bg-orange-500/10 text-orange-400'
                  }`}>
                    {d.status === 'Completed' ? <CheckCircle2 className="h-3 w-3" /> : <Clock className="h-3 w-3" />}
                    {d.status}
                  </span>
                  <button
                    onClick={() => deleteDrill(d.id)}
                    className="p-1.5 rounded-lg text-slate-500 hover:bg-red-500/10 hover:text-red-500 transition-colors"
                    title="Delete drill log"
                  >
                    <Trash2 className="h-4.5 w-4.5" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
